#!/usr/bin/env bash

get_partition() {
    echo "Available partitions:" >&2
    lsblk >&2
    read -p "Please enter the $1 partition (e.g., /dev/sda1): " PARTITION
    echo "$PARTITION"
}

BOOT_PARTITION=${1:-$(get_partition "BOOT")}
ROOT_PARTITION=${2:-$(get_partition "ROOT")}
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

mount "$ROOT_PARTITION" /mnt
mkdir /mnt/boot
mount "$BOOT_PARTITION" /mnt/boot

pacstrap /mnt base base-devel linux linux-firmware networkmanager openssh git neovim

genfstab -U /mnt > /mnt/etc/fstab

cp "${SCRIPT_DIR}/chroot" /mnt/chroot

arch-chroot /mnt bash /chroot

rm /mnt/chroot
