#!/usr/bin/env bash

ROOT_PARTITION="$(df | awk '/\/$/ {print $1}')"
SEPERATOR="================="

bootctl --path=/boot install
echo -e "timeout 3\ndefault arch" > /boot/loader/loader.conf
echo -e "title Arch Linux\nlinux /vmlinuz-linux\ninitrd /initramfs-linux.img\noptions root=${ROOT_PARTITION} rw" > /boot/loader/entries/arch.conf


echo "$SEPERATOR"
echo "Set root password"
passwd


echo "$SEPERATOR"
read -p "Set hostname: " HOSTNAME

echo "Writing /etc/hostname"
echo "$HOSTNAME" > /etc/hostname

echo "Writing /etc/hosts"
echo -e "127.0.0.1\tlocalhost\n::1\tlocalhost" > /etc/hosts


echo "$SEPERATOR"
read -p "Set username: " USERNAME
useradd -mG wheel,audio,video "$USERNAME"
passwd "$USERNAME"

echo "Writing /etc/sudoers"
sed 's/# \(%wheel ALL=(ALL) ALL\)/\1/' /etc/sudoers | (EDITOR='tee' visudo)


systemctl enable NetworkManager
systemctl enable sshd

sudo -u "$USERNAME" -s
