#!/usr/bin/env bash

ROOT_PARTITION="$(df | awk '/\/$/ {print $1}')"
SEPARATOR="================="
DOTFILES_REPO="icalvin102/.dotfiles.git"

bootctl --path=/boot install
echo -e "timeout 3\ndefault arch" > /boot/loader/loader.conf
echo -e "title Arch Linux\nlinux /vmlinuz-linux\ninitrd /initramfs-linux.img\noptions root=${ROOT_PARTITION} rw" > /boot/loader/entries/arch.conf

ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
hwclock --systohc

echo 'LANG=en_US.UTF-8' > /etc/locale.conf
sed -i 's/^#\(de_DE.UTF-8\|en_US.UTF-8\)/\1/' /etc/locale.gen
locale-gen

echo "Writing /etc/hosts"
echo -e "127.0.0.1\tlocalhost\n::1\tlocalhost" > /etc/hosts


echo "$SEPARATOR"
echo "Set root password"
passwd

echo "$SEPARATOR"
read -p "Set hostname: " HOSTNAME

echo "Writing /etc/hostname"
echo "$HOSTNAME" > /etc/hostname


echo "$SEPARATOR"
read -p "Set username: " USERNAME
useradd -mG wheel,audio,video,storage "$USERNAME"
passwd "$USERNAME"

echo "Writing /etc/sudoers"
echo '%wheel ALL=(ALL) ALL' | EDITOR='tee -a' visudo >/dev/null

systemctl enable NetworkManager
systemctl enable sshd

read -p "Do you want to install the dotfiles? (y/n): " INSTALL_DOTFILES

if [[ "$INSTALL_DOTFILES" =~ ^[Yy]$ ]]; then
  sudo -u "$USERNAME" bash -c "git clone https://github.com/${DOTFILES_REPO} ~/.dotfiles"
  sudo -u "$USERNAME" bash -c "git -C ~/.dotfiles remote set-url origin git@github.com:${DOTFILES_REPO}"
  sudo -u "$USERNAME" bash -c "bash ~/.dotfiles/.install/postinstall"
fi

sudo -u "$USERNAME" -s
