#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DOTFILES_DIR="$SCRIPT_DIR/.."
[ -f "$SCRIPT_DIR/pacman_pkg_list" ] && PACMAN_PKGS=$(< "$SCRIPT_DIR/pacman_pkg_list")
[ -f "$SCRIPT_DIR/yay_pkg_list" ] && YAY_PKGS=$(< "$SCRIPT_DIR/yay_pkg_list")

function install_yay() {
  if command -v yay &> /dev/null; then
    echo "'yay' is already installed. Skipping installation."
  else
    echo "Installing 'yay' AUR helper..."
    cd /tmp
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
    cd ~
  fi
}

sudo pacman -S --needed --noconfirm nvidia nvidia-utils nvidia-settings

sudo pacman -S hyprland docker stow keyd $PACMAN_PKGS

sudo systemctl enable --now docker.service
sudo usermod -aG docker "$USER"
sudo fc-cache -fv

sudo systemctl enable --now keyd
ln -s /usr/share/keyd/keyd.compose ~/.XCompose 

install_yay

yay -S --needed --noconfirm $YAY_PKGS

mkdir -p ~/.config ~/.local ~/.cache

rm ~/.bash*
cd "$DOTFILES_DIR/home"
stow -t ~ *

cd "$DOTFILES_DIR/system"
stow -t / *

sudo mkinitcpio -P
