#!/bin/bash

trap 'update' 5
S='#'

get_date(){
    echo "$(date +%Y.%m.%d\ %H:%M)"
}

get_volume(){
    echo "Vol $(pamixer --get-volume)%"
}

get_battery(){
    CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
    STATUS=$(sed 's/Not charging/~/;s/Charging/+/;s/Discharging/=/' /sys/class/power_supply/BAT0/status)
    echo "Bat $STATUS $CAPACITY%"
}

get_wifi_ssid(){
    echo "SSID: $(nmcli -t -f active,ssid dev wifi | grep -P -o '(?<=^yes:).+')"
}

update(){
    xsetroot -name " $(get_wifi_ssid) $S $(get_battery) $S $(get_volume) $S $(get_date) " &
    wait
}

while true 
do
    update
    sleep 30 &
    wait
done
